dist: bionic
language: csharp
env:
  global:
    - PATH="$PATH:$HOME/.dotnet/tools"

install:
  - dotnet tool restore 

script:
 - dotnet paket install
 - dotnet restore
 - dotnet build
 - dotnet test

jobs:
    include:
        - dotnet: "3.0.100"
          mono: latest
